spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-jpa-pk-test
    username: postgres
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        use_sql_comments: true
        format_sql: true
        use-new-id-generator-mappings: false
